export type ArticleRef = {
  slug: string;
  title: string;
};

const REFS: Array<{
  surah: number;
  ayatStart: number;
  ayatEnd: number;
  slug: string;
  title: string;
}> = [
  {
    surah: 18,
    ayatStart: 83,
    ayatEnd: 98,
    slug: "dzulqarnain",
    title: "Dzulqarnain dan Teks yang Sudah Ada Sebelumnya",
  },
  {
    surah: 2,
    ayatStart: 173,
    ayatEnd: 173,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  {
    surah: 5,
    ayatStart: 3,
    ayatEnd: 3,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  {
    surah: 53,
    ayatStart: 3,
    ayatEnd: 4,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  // babi — verses mentioned in article but missing from refs
  {
    surah: 9,
    ayatStart: 108,
    ayatEnd: 108,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  {
    surah: 74,
    ayatStart: 4,
    ayatEnd: 4,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  // Artikel: Etika Abad Ke-7 yang Dianggap Abadi
  // intro verses (universalist claims used as contrast)
  {
    surah: 2,
    ayatStart: 143,
    ayatEnd: 143,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 49,
    ayatStart: 13,
    ayatEnd: 13,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 32,
    ayatEnd: 32,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 9,
    ayatStart: 5,
    ayatEnd: 5,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 9,
    ayatStart: 30,
    ayatEnd: 30,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 2,
    ayatStart: 191,
    ayatEnd: 191,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 2,
    ayatStart: 65,
    ayatEnd: 65,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 2,
    ayatStart: 282,
    ayatEnd: 282,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 11,
    ayatEnd: 11,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 24,
    ayatEnd: 24,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 34,
    ayatEnd: 34,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 36,
    ayatEnd: 36,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 89,
    ayatEnd: 89,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 155,
    ayatEnd: 157,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 38,
    ayatEnd: 38,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 51,
    ayatEnd: 51,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 60,
    ayatEnd: 60,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 3,
    ayatStart: 28,
    ayatEnd: 28,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 23,
    ayatStart: 5,
    ayatEnd: 6,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 24,
    ayatStart: 2,
    ayatEnd: 2,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 47,
    ayatStart: 4,
    ayatEnd: 4,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 55,
    ayatStart: 72,
    ayatEnd: 72,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 56,
    ayatStart: 35,
    ayatEnd: 37,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 78,
    ayatStart: 33,
    ayatEnd: 33,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 98,
    ayatStart: 6,
    ayatEnd: 6,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  // Artikel: Waraqah bin Naufal dan Asal-Usul Wahyu
  {
    surah: 6,
    ayatStart: 19,
    ayatEnd: 19,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 10,
    ayatStart: 37,
    ayatEnd: 37,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 17,
    ayatStart: 105,
    ayatEnd: 105,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 41,
    ayatStart: 42,
    ayatEnd: 42,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 56,
    ayatStart: 77,
    ayatEnd: 80,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  // Artikel: Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi
  {
    surah: 33,
    ayatStart: 50,
    ayatEnd: 50,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 51,
    ayatEnd: 51,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 37,
    ayatEnd: 37,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 53,
    ayatEnd: 53,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 6,
    ayatEnd: 6,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 57,
    ayatEnd: 57,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 30,
    ayatEnd: 30,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 32,
    ayatEnd: 32,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 26,
    ayatEnd: 27,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 66,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 66,
    ayatStart: 3,
    ayatEnd: 5,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 8,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 8,
    ayatStart: 41,
    ayatEnd: 41,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 59,
    ayatStart: 6,
    ayatEnd: 7,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 43,
    ayatEnd: 43,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 61,
    ayatEnd: 61,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 63,
    ayatEnd: 63,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 103,
    ayatEnd: 103,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 49,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 49,
    ayatStart: 2,
    ayatEnd: 2,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 59,
    ayatEnd: 59,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 65,
    ayatEnd: 65,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 80,
    ayatEnd: 80,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 105,
    ayatEnd: 105,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 5,
    ayatStart: 49,
    ayatEnd: 49,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 68,
    ayatStart: 4,
    ayatEnd: 4,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 80,
    ayatStart: 1,
    ayatEnd: 10,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 111,
    ayatStart: 1,
    ayatEnd: 5,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  // Artikel: Ritual yang Tidak Ada dalam Al-Quran (lempar jumrah)
  {
    surah: 2,
    ayatStart: 196,
    ayatEnd: 203,
    slug: "lempar-jumrah",
    title: "Ritual yang Tidak Ada dalam Al-Quran",
  },
  {
    surah: 22,
    ayatStart: 27,
    ayatEnd: 37,
    slug: "lempar-jumrah",
    title: "Ritual yang Tidak Ada dalam Al-Quran",
  },
  {
    surah: 5,
    ayatStart: 2,
    ayatEnd: 2,
    slug: "lempar-jumrah",
    title: "Ritual yang Tidak Ada dalam Al-Quran",
  },
  // Artikel: Kaaba, Allah, dan Apa yang Ada Sebelumnya
  {
    surah: 53,
    ayatStart: 19,
    ayatEnd: 23,
    slug: "warisan-pagan-arab",
    title: "Kaaba, Allah, dan Apa yang Ada Sebelumnya",
  },
  {
    surah: 29,
    ayatStart: 61,
    ayatEnd: 61,
    slug: "warisan-pagan-arab",
    title: "Kaaba, Allah, dan Apa yang Ada Sebelumnya",
  },
  {
    surah: 68,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "warisan-pagan-arab",
    title: "Kaaba, Allah, dan Apa yang Ada Sebelumnya",
  },
];

export function getArticlesForVerse(
  surahId: number,
  ayahNumber: number,
): ArticleRef[] {
  const seen = new Set<string>();
  return REFS.filter((r) => {
    if (r.surah !== surahId || ayahNumber < r.ayatStart || ayahNumber > r.ayatEnd) return false;
    if (seen.has(r.slug)) return false;
    seen.add(r.slug);
    return true;
  }).map((r) => ({ slug: r.slug, title: r.title }));
}
