export type ArticleRef = {
  slug: string;
  title: string;
};

const REFS: Array<{
  surah: number;
  ayatStart: number;
  ayatEnd: number;
  slug: string;
  title: string;
}> = [
  {
    surah: 18,
    ayatStart: 83,
    ayatEnd: 98,
    slug: "dzulqarnain",
    title: "Dzulqarnain dan Teks yang Sudah Ada Sebelumnya",
  },
  {
    surah: 2,
    ayatStart: 173,
    ayatEnd: 173,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  {
    surah: 5,
    ayatStart: 3,
    ayatEnd: 3,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  {
    surah: 53,
    ayatStart: 3,
    ayatEnd: 4,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  // babi — verses mentioned in article but missing from refs
  {
    surah: 9,
    ayatStart: 108,
    ayatEnd: 108,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  {
    surah: 74,
    ayatStart: 4,
    ayatEnd: 4,
    slug: "babi-dan-kencing-unta",
    title: "Babi Matang, Kencing Unta, dan Standar yang Tidak Konsisten",
  },
  // Artikel: Etika Abad Ke-7 yang Dianggap Abadi
  // intro verses (universalist claims used as contrast)
  {
    surah: 2,
    ayatStart: 143,
    ayatEnd: 143,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 49,
    ayatStart: 13,
    ayatEnd: 13,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 32,
    ayatEnd: 32,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 9,
    ayatStart: 5,
    ayatEnd: 5,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 9,
    ayatStart: 30,
    ayatEnd: 30,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 2,
    ayatStart: 191,
    ayatEnd: 191,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 2,
    ayatStart: 65,
    ayatEnd: 65,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 2,
    ayatStart: 282,
    ayatEnd: 282,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 11,
    ayatEnd: 11,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 24,
    ayatEnd: 24,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 34,
    ayatEnd: 34,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 36,
    ayatEnd: 36,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 89,
    ayatEnd: 89,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 4,
    ayatStart: 155,
    ayatEnd: 157,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 38,
    ayatEnd: 38,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 51,
    ayatEnd: 51,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 5,
    ayatStart: 60,
    ayatEnd: 60,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 3,
    ayatStart: 28,
    ayatEnd: 28,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 23,
    ayatStart: 5,
    ayatEnd: 6,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 24,
    ayatStart: 2,
    ayatEnd: 2,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 47,
    ayatStart: 4,
    ayatEnd: 4,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 55,
    ayatStart: 72,
    ayatEnd: 72,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 56,
    ayatStart: 35,
    ayatEnd: 37,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 78,
    ayatStart: 33,
    ayatEnd: 33,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  {
    surah: 98,
    ayatStart: 6,
    ayatEnd: 6,
    slug: "sistem-moral-quran",
    title: "Etika Abad Ke-7 yang Dianggap Abadi",
  },
  // Artikel: Waraqah bin Naufal dan Asal-Usul Wahyu
  {
    surah: 6,
    ayatStart: 19,
    ayatEnd: 19,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 10,
    ayatStart: 37,
    ayatEnd: 37,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 17,
    ayatStart: 105,
    ayatEnd: 105,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 41,
    ayatStart: 42,
    ayatEnd: 42,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  {
    surah: 56,
    ayatStart: 77,
    ayatEnd: 80,
    slug: "waraqah-dan-wahyu",
    title: "Waraqah bin Naufal dan Asal-Usul Wahyu",
  },
  // Artikel: Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi
  {
    surah: 33,
    ayatStart: 50,
    ayatEnd: 50,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 51,
    ayatEnd: 51,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 37,
    ayatEnd: 37,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 53,
    ayatEnd: 53,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 6,
    ayatEnd: 6,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 57,
    ayatEnd: 57,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 30,
    ayatEnd: 30,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 32,
    ayatEnd: 32,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 33,
    ayatStart: 26,
    ayatEnd: 27,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 66,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 66,
    ayatStart: 3,
    ayatEnd: 5,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 8,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 8,
    ayatStart: 41,
    ayatEnd: 41,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 59,
    ayatStart: 6,
    ayatEnd: 7,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 43,
    ayatEnd: 43,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 61,
    ayatEnd: 61,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 63,
    ayatEnd: 63,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 9,
    ayatStart: 103,
    ayatEnd: 103,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 49,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 49,
    ayatStart: 2,
    ayatEnd: 2,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 59,
    ayatEnd: 59,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 65,
    ayatEnd: 65,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 80,
    ayatEnd: 80,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 4,
    ayatStart: 105,
    ayatEnd: 105,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 5,
    ayatStart: 49,
    ayatEnd: 49,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 68,
    ayatStart: 4,
    ayatEnd: 4,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 80,
    ayatStart: 1,
    ayatEnd: 10,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  {
    surah: 111,
    ayatStart: 1,
    ayatEnd: 5,
    slug: "wahyu-konvenien",
    title: "Ketika Wahyu Mengikuti Kepentingan Pribadi Nabi",
  },
  // Artikel: Ritual yang Tidak Ada dalam Al-Quran (lempar jumrah)
  {
    surah: 2,
    ayatStart: 196,
    ayatEnd: 203,
    slug: "lempar-jumrah",
    title: "Ritual yang Tidak Ada dalam Al-Quran",
  },
  {
    surah: 22,
    ayatStart: 27,
    ayatEnd: 37,
    slug: "lempar-jumrah",
    title: "Ritual yang Tidak Ada dalam Al-Quran",
  },
  {
    surah: 5,
    ayatStart: 2,
    ayatEnd: 2,
    slug: "lempar-jumrah",
    title: "Ritual yang Tidak Ada dalam Al-Quran",
  },
  // Artikel: Kaaba, Allah, dan Apa yang Ada Sebelumnya
  {
    surah: 53,
    ayatStart: 19,
    ayatEnd: 23,
    slug: "warisan-pagan-arab",
    title: "Kaaba, Allah, dan Apa yang Ada Sebelumnya",
  },
  {
    surah: 29,
    ayatStart: 61,
    ayatEnd: 61,
    slug: "warisan-pagan-arab",
    title: "Kaaba, Allah, dan Apa yang Ada Sebelumnya",
  },
  {
    surah: 68,
    ayatStart: 1,
    ayatEnd: 1,
    slug: "warisan-pagan-arab",
    title: "Kaaba, Allah, dan Apa yang Ada Sebelumnya",
  },
  // Artikel: Apa yang Terlihat Setelah Teks Diperiksa (kritik-quran)
  { surah: 2, ayatStart: 189, ayatEnd: 189, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 2, ayatStart: 219, ayatEnd: 219, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 17, ayatStart: 85, ayatEnd: 85, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 15, ayatStart: 9, ayatEnd: 9, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 7, ayatStart: 54, ayatEnd: 54, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 41, ayatStart: 9, ayatEnd: 12, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 2, ayatStart: 29, ayatEnd: 29, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 79, ayatStart: 27, ayatEnd: 30, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 2, ayatStart: 34, ayatEnd: 34, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 18, ayatStart: 50, ayatEnd: 50, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 28, ayatStart: 40, ayatEnd: 40, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 10, ayatStart: 90, ayatEnd: 92, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 21, ayatStart: 76, ayatEnd: 76, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 11, ayatStart: 42, ayatEnd: 43, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 2, ayatStart: 256, ayatEnd: 256, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 9, ayatStart: 29, ayatEnd: 29, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 9, ayatStart: 115, ayatEnd: 115, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 14, ayatStart: 4, ayatEnd: 4, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 39, ayatStart: 23, ayatEnd: 23, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 2, ayatStart: 47, ayatEnd: 48, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 2, ayatStart: 255, ayatEnd: 255, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 20, ayatStart: 109, ayatEnd: 109, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 5, ayatStart: 90, ayatEnd: 90, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 23, ayatStart: 12, ayatEnd: 14, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 86, ayatStart: 5, ayatEnd: 7, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 67, ayatStart: 5, ayatEnd: 5, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 21, ayatStart: 32, ayatEnd: 32, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 21, ayatStart: 31, ayatEnd: 31, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 16, ayatStart: 15, ayatEnd: 15, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 78, ayatStart: 6, ayatEnd: 7, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 25, ayatStart: 61, ayatEnd: 61, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 71, ayatStart: 16, ayatEnd: 16, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 51, ayatStart: 49, ayatEnd: 49, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 16, ayatStart: 68, ayatEnd: 69, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 2, ayatStart: 23, ayatEnd: 23, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  { surah: 17, ayatStart: 88, ayatEnd: 88, slug: "kritik-quran", title: "Apa yang Terlihat Setelah Teks Diperiksa" },
  // Artikel: Siapa yang Hampir Disembelih Ibrahim?
  { surah: 37, ayatStart: 102, ayatEnd: 102, slug: "kurban-ibrahim", title: "Siapa yang Hampir Disembelih Ibrahim?" },
  { surah: 37, ayatStart: 107, ayatEnd: 107, slug: "kurban-ibrahim", title: "Siapa yang Hampir Disembelih Ibrahim?" },
  { surah: 16, ayatStart: 89, ayatEnd: 89, slug: "kurban-ibrahim", title: "Siapa yang Hampir Disembelih Ibrahim?" },
  { surah: 6, ayatStart: 114, ayatEnd: 114, slug: "kurban-ibrahim", title: "Siapa yang Hampir Disembelih Ibrahim?" },
  { surah: 5, ayatStart: 101, ayatEnd: 101, slug: "kurban-ibrahim", title: "Siapa yang Hampir Disembelih Ibrahim?" },
  { surah: 22, ayatStart: 37, ayatEnd: 37, slug: "kurban-ibrahim", title: "Siapa yang Hampir Disembelih Ibrahim?" },
  // Artikel: Orang yang Tidak Bisa Ditebus (an-nadr-ibn-al-harith)
  { surah: 8, ayatStart: 31, ayatEnd: 31, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  { surah: 68, ayatStart: 15, ayatEnd: 15, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  { surah: 25, ayatStart: 5, ayatEnd: 5, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  { surah: 83, ayatStart: 13, ayatEnd: 13, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  { surah: 16, ayatStart: 24, ayatEnd: 24, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  { surah: 2, ayatStart: 23, ayatEnd: 24, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  { surah: 17, ayatStart: 88, ayatEnd: 88, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  { surah: 73, ayatStart: 10, ayatEnd: 10, slug: "an-nadr-ibn-al-harith", title: "Orang yang Tidak Bisa Ditebus" },
  // Artikel: Allah di Mekah, Allah di Madinah (allah-mekah-madinah)
  { surah: 16, ayatStart: 67, ayatEnd: 67, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 2, ayatStart: 219, ayatEnd: 219, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 4, ayatStart: 43, ayatEnd: 43, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 5, ayatStart: 90, ayatEnd: 90, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 2, ayatStart: 256, ayatEnd: 256, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 10, ayatStart: 99, ayatEnd: 99, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 4, ayatStart: 89, ayatEnd: 89, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 29, ayatStart: 46, ayatEnd: 46, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 9, ayatStart: 29, ayatEnd: 29, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 9, ayatStart: 30, ayatEnd: 30, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 33, ayatStart: 35, ayatEnd: 35, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 4, ayatStart: 34, ayatEnd: 34, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 4, ayatStart: 11, ayatEnd: 11, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 2, ayatStart: 282, ayatEnd: 282, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 21, ayatStart: 107, ayatEnd: 107, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 6, ayatStart: 108, ayatEnd: 108, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  { surah: 48, ayatStart: 29, ayatEnd: 29, slug: "allah-mekah-madinah", title: "Allah di Mekah, Allah di Madinah" },
  // Artikel: Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya (ashabul-kahfi)
  { surah: 18, ayatStart: 9, ayatEnd: 9, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  { surah: 18, ayatStart: 13, ayatEnd: 13, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  { surah: 18, ayatStart: 18, ayatEnd: 18, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  { surah: 18, ayatStart: 19, ayatEnd: 19, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  { surah: 18, ayatStart: 22, ayatEnd: 22, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  { surah: 18, ayatStart: 25, ayatEnd: 25, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  { surah: 11, ayatStart: 49, ayatEnd: 49, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  { surah: 12, ayatStart: 3, ayatEnd: 3, slug: "ashabul-kahfi", title: "Gua, Anjing, dan Naskah yang Sudah Ada Sembilan Puluh Tahun Sebelumnya" },
  // Artikel: Kata yang Satu Ini (nikah-mutah)
  { surah: 4, ayatStart: 24, ayatEnd: 24, slug: "nikah-mutah", title: "Kata yang Satu Ini" },
  { surah: 2, ayatStart: 219, ayatEnd: 219, slug: "nikah-mutah", title: "Kata yang Satu Ini" },
  { surah: 5, ayatStart: 90, ayatEnd: 90, slug: "nikah-mutah", title: "Kata yang Satu Ini" },
  { surah: 17, ayatStart: 32, ayatEnd: 32, slug: "nikah-mutah", title: "Kata yang Satu Ini" },
  { surah: 66, ayatStart: 1, ayatEnd: 1, slug: "nikah-mutah", title: "Kata yang Satu Ini" },
  // Artikel: Tidak Ada Paksaan (tidak-ada-paksaan)
  { surah: 2, ayatStart: 256, ayatEnd: 256, slug: "tidak-ada-paksaan", title: "Tidak Ada Paksaan" },
  { surah: 4, ayatStart: 89, ayatEnd: 89, slug: "tidak-ada-paksaan", title: "Tidak Ada Paksaan" },
  { surah: 18, ayatStart: 29, ayatEnd: 29, slug: "tidak-ada-paksaan", title: "Tidak Ada Paksaan" },
  { surah: 4, ayatStart: 137, ayatEnd: 137, slug: "tidak-ada-paksaan", title: "Tidak Ada Paksaan" },
  { surah: 4, ayatStart: 145, ayatEnd: 145, slug: "tidak-ada-paksaan", title: "Tidak Ada Paksaan" },
  // Artikel: Bumi yang Dihamparkan (bumi-datar)
  { surah: 88, ayatStart: 20, ayatEnd: 20, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  { surah: 71, ayatStart: 19, ayatEnd: 19, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  { surah: 2, ayatStart: 22, ayatEnd: 22, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  { surah: 20, ayatStart: 53, ayatEnd: 53, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  { surah: 15, ayatStart: 19, ayatEnd: 19, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  { surah: 18, ayatStart: 86, ayatEnd: 86, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  { surah: 2, ayatStart: 187, ayatEnd: 187, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  { surah: 2, ayatStart: 149, ayatEnd: 149, slug: "bumi-datar", title: "Bumi yang Dihamparkan" },
  // Artikel: Mitos "Preservasi Sempurna" Al-Quran
  { surah: 12, ayatStart: 2, ayatEnd: 2, slug: "preservasi-quran", title: 'Mitos "Preservasi Sempurna" Al-Quran' },
  { surah: 2, ayatStart: 238, ayatEnd: 238, slug: "preservasi-quran", title: 'Mitos "Preservasi Sempurna" Al-Quran' },
  { surah: 5, ayatStart: 6, ayatEnd: 6, slug: "preservasi-quran", title: 'Mitos "Preservasi Sempurna" Al-Quran' },
  { surah: 33, ayatStart: 6, ayatEnd: 6, slug: "preservasi-quran", title: 'Mitos "Preservasi Sempurna" Al-Quran' },
  { surah: 2, ayatStart: 144, ayatEnd: 144, slug: "preservasi-quran", title: 'Mitos "Preservasi Sempurna" Al-Quran' },
  { surah: 15, ayatStart: 9, ayatEnd: 9, slug: "preservasi-quran", title: 'Mitos "Preservasi Sempurna" Al-Quran' },
];

export function getArticlesForVerse(
  surahId: number,
  ayahNumber: number,
): ArticleRef[] {
  const seen = new Set<string>();
  return REFS.filter((r) => {
    if (r.surah !== surahId || ayahNumber < r.ayatStart || ayahNumber > r.ayatEnd) return false;
    if (seen.has(r.slug)) return false;
    seen.add(r.slug);
    return true;
  }).map((r) => ({ slug: r.slug, title: r.title }));
}
