export type Section = {
  title: string;
  paragraphs: string[];
};

export type EssayContent = {
  lead: string;
  problemMap: string;
  sections: Section[];
  verseRefs: number[];
};

export type BedahSuratItem = {
  slug: string;
  number: string;
  surahNumber: number;
  title: string;
  subtitle: string;
  excerpt: string;
  range: string;
  classification: string;
  readTime: string;
};

export const bedahSuratItems: BedahSuratItem[] = [
  {
    slug: "al-fatihah",
    number: "001",
    surahNumber: 1,
    title: "Al-Fatihah",
    subtitle: "Doa Pembuka yang Membagi Jalan Manusia",
    excerpt:
      "Al-Fatihah tampak seperti doa universal. Tetapi di bagian paling akhir, ia mulai membangun peta moral yang sempit: jalan yang diberi nikmat, jalan yang dimurkai, dan jalan yang sesat.",
    range: "Al-Fatihah 1:1-7",
    classification: "Makkiyah",
    readTime: "7 menit",
  },
  {
    slug: "al-baqarah",
    number: "002",
    surahNumber: 2,
    title: "Al-Baqarah",
    subtitle: "Kitab Hukum, Memori Konflik, dan Ayat yang Direvisi",
    excerpt:
      "Al-Baqarah bukan hanya surat panjang. Ia adalah ruang tempat hukum keluarga, perang, identitas kelompok, cerita Bani Israel, riba, qisas, dan naskh duduk berdampingan.",
    range: "Al-Baqarah 2:1-286",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "ali-imran",
    number: "003",
    surahNumber: 3,
    title: "Ali Imran",
    subtitle: "Isa, Ahli Kitab, dan Politik Identitas Iman",
    excerpt:
      "Ali Imran bergerak di antara polemik tentang Isa, kritik terhadap Ahli Kitab, dan pembacaan ulang kekalahan Uhud. Surat ini terasa seperti teks yang lahir di tengah debat sosial.",
    range: "Ali Imran 3:1-200",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "an-nisa",
    number: "004",
    surahNumber: 4,
    title: "An-Nisa'",
    subtitle: "Keluarga, Warisan, dan Kuasa Laki-Laki",
    excerpt:
      "An-Nisa' sering dibaca sebagai surat tentang keluarga dan perempuan. Tetapi di baliknya ada struktur hukum yang menempatkan tubuh, warisan, relasi, dan otoritas rumah tangga dalam hierarki patriarkal.",
    range: "An-Nisa 4:1-176",
    classification: "Madaniyah",
    readTime: "13 menit",
  },
  {
    slug: "al-maidah",
    number: "005",
    surahNumber: 5,
    title: "Al-Ma'idah",
    subtitle: "Hukum Akhir, Batas Komunitas, dan Meja dari Langit",
    excerpt:
      "Al-Ma'idah memadukan aturan makanan, wudu, hukuman, relasi dengan Ahli Kitab, dan kisah hidangan dari langit. Surat ini terasa seperti penegasan batas pada fase komunitas yang makin mapan.",
    range: "Al-Ma'idah 5:1-120",
    classification: "Madaniyah",
    readTime: "13 menit",
  },
  {
    slug: "al-anam",
    number: "006",
    surahNumber: 6,
    title: "Al-An'am",
    subtitle: "Tanda Alam, Takdir, dan Argumen yang Tertutup",
    excerpt:
      "Al-An'am membela tauhid dengan tanda-tanda alam, kritik terhadap berhala, dan bantahan pada aturan makanan kaum musyrik. Tetapi argumennya berkali-kali menutup ruang skeptis lewat takdir dan vonis hati.",
    range: "Al-An'am 6:1-165",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "al-araf",
    number: "007",
    surahNumber: 7,
    title: "Al-A'raf",
    subtitle: "Kota yang Dihancurkan dan Manusia yang Disesatkan",
    excerpt:
      "Al-A'raf bergerak dari Adam dan Iblis menuju rangkaian umat terdahulu, Musa-Firaun, dan peringatan akhirat. Polanya keras: nabi datang, penolak dihukum, dan kesesatan dikaitkan dengan kehendak Allah.",
    range: "Al-A'raf 7:1-206",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "al-anfal",
    number: "008",
    surahNumber: 8,
    title: "Al-Anfal",
    subtitle: "Rampasan Perang dan Teologi Kemenangan",
    excerpt:
      "Al-Anfal lahir dari bayang Perang Badar: rampasan, malaikat, disiplin perang, tawanan, dan loyalitas komunitas. Surat ini memperlihatkan bagaimana kekerasan diberi bahasa ibadah dan kemenangan.",
    range: "Al-Anfal 8:1-75",
    classification: "Madaniyah",
    readTime: "13 menit",
  },
  {
    slug: "at-taubah",
    number: "009",
    surahNumber: 9,
    title: "At-Taubah",
    subtitle: "Ultimatum, Jizyah, dan Politik Loyalitas",
    excerpt:
      "At-Taubah adalah salah satu surat paling keras: pemutusan perjanjian, ayat pedang, jizyah, pembacaan munafik, dan loyalitas perang. Surat ini memperlihatkan agama ketika menjadi kekuasaan komunal.",
    range: "At-Taubah 9:1-129",
    classification: "Madaniyah",
    readTime: "14 menit",
  },
  {
    slug: "yunus",
    number: "010",
    surahNumber: 10,
    title: "Yunus",
    subtitle: "Tanda Alam, Ancaman, dan Iman yang Diizinkan",
    excerpt:
      "Yunus memakai alam, kisah Nuh, Musa-Firaun, dan kaum Yunus untuk membela wahyu. Tetapi di baliknya ada ketegangan besar antara tuntutan iman dan klaim bahwa iman bergantung izin Allah.",
    range: "Yunus 10:1-109",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "hud",
    number: "011",
    surahNumber: 11,
    title: "Hud",
    subtitle: "Sejarah Hukuman dan Kota-Kota yang Dihapus",
    excerpt:
      "Hud menyusun rangkaian nabi dan umat terdahulu dalam pola yang hampir sama: utusan datang, kaum meragukan, lalu hukuman turun. Surat ini kuat sebagai peringatan, tetapi berat sebagai etika keadilan.",
    range: "Hud 11:1-123",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "yusuf",
    number: "012",
    surahNumber: 12,
    title: "Yusuf",
    subtitle: "Kisah Indah, Trauma Keluarga, dan Kuasa yang Licin",
    excerpt:
      "Yusuf disebut kisah terbaik, tetapi jika dibaca pelan, ia penuh favoritisme keluarga, perbudakan, fitnah seksual, penjara, tafsir mimpi, manipulasi kuasa, dan rekonsiliasi yang terlalu cepat.",
    range: "Yusuf 12:1-111",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "ar-rad",
    number: "013",
    surahNumber: 13,
    title: "Ar-Ra'd",
    subtitle: "Petir, Takdir, dan Bukti yang Selalu Mundur",
    excerpt:
      "Ar-Ra'd membangun argumen dari langit, bumi, guruh, janin, dan pergantian alam. Tetapi tuntutan bukti berulang kali dijawab dengan takdir, ancaman, atau kesaksian yang tidak bisa diperiksa.",
    range: "Ar-Ra'd 13:1-43",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "ibrahim",
    number: "014",
    surahNumber: 14,
    title: "Ibrahim",
    subtitle: "Bahasa Wahyu, Takdir Sesat, dan Doa Kota Suci",
    excerpt:
      "Ibrahim bergerak dari kegelapan-cahaya, bahasa rasul, kisah Musa, neraka yang grafis, pohon baik-buruk, sampai doa Ibrahim untuk Makkah. Di baliknya ada takdir, eksklusivitas, dan politik asal-usul.",
    range: "Ibrahim 14:1-52",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "al-hijr",
    number: "015",
    surahNumber: 15,
    title: "Al-Hijr",
    subtitle: "Quran yang Dijaga, Langit yang Dilempari, dan Iblis yang Dibiarkan",
    excerpt:
      "Al-Hijr memuat klaim pemeliharaan Quran, kosmologi meteor yang mengejar setan, penciptaan Adam, izin bagi Iblis, Luth, dan kota-kota yang dihancurkan sebagai tanda.",
    range: "Al-Hijr 15:1-99",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "an-nahl",
    number: "016",
    surahNumber: 16,
    title: "An-Nahl",
    subtitle: "Nikmat, Alam, Lebah, dan Wahyu yang Direvisi",
    excerpt:
      "An-Nahl membangun argumen dari ternak, hujan, gunung, laut, lebah, susu, dan makanan. Tetapi surat nikmat ini juga menyimpan problem antroposentrisme, takdir, gender, naskh, dan klaim bahasa Arab.",
    range: "An-Nahl 16:1-128",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "al-isra",
    number: "017",
    surahNumber: 17,
    title: "Al-Isra'",
    subtitle: "Perjalanan Malam, Etika Sosial, dan Bukti yang Ditolak",
    excerpt:
      "Al-Isra' membuka dengan perjalanan malam, lalu bergerak ke Bani Israel, etika sosial, catatan amal, Iblis, ruh, tantangan Quran, dan tuntutan mukjizat yang tidak pernah dipenuhi.",
    range: "Al-Isra 17:1-111",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "al-kahf",
    number: "018",
    surahNumber: 18,
    title: "Al-Kahf",
    subtitle: "Legenda, Hikmah Tersembunyi, dan Matahari di Lumpur",
    excerpt:
      "Al-Kahf memuat Ashabul Kahfi, dua pemilik kebun, Musa-Khidr, dan Dzulqarnain. Surat ini kuat sebagai kumpulan cerita, tetapi problematik ketika legenda dan kekerasan moral dibaca sebagai sejarah suci.",
    range: "Al-Kahf 18:1-110",
    classification: "Makkiyah",
    readTime: "15 menit",
  },
  {
    slug: "maryam",
    number: "019",
    surahNumber: 19,
    title: "Maryam",
    subtitle: "Kelahiran Ajaib, Tubuh Perempuan, dan Polemik Anak Tuhan",
    excerpt:
      "Maryam memuat Zakariya, Yahya, Maryam, Isa bayi berbicara, Ibrahim, dan penolakan anak Tuhan. Surat ini lembut di permukaan, tetapi menyimpan masalah sejarah, tubuh perempuan, dan eksklusivitas teologis.",
    range: "Maryam 19:1-98",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "taha",
    number: "020",
    surahNumber: 20,
    title: "Taha",
    subtitle: "Musa, Mukjizat, dan Ketakutan sebagai Pendidikan Iman",
    excerpt:
      "Taha berpusat pada Musa: panggilan di lembah suci, tongkat-ular, Firaun, penyihir, laut, Samiri, lalu Adam-Iblis. Surat ini memperlihatkan narasi mukjizat yang kuat sekaligus rapuh secara etika.",
    range: "Taha 20:1-135",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "al-anbiya",
    number: "021",
    surahNumber: 21,
    title: "Al-Anbiya'",
    subtitle: "Parade Nabi, Kosmologi Lama, dan Keadilan yang Tidak Ditanya",
    excerpt:
      "Al-Anbiya' mengumpulkan banyak nabi, argumen tauhid, langit-bumi, gunung, Ya'juj-Ma'juj, dan neraka. Surat ini bertanya tentang manusia, tetapi memberi Tuhan posisi yang tidak boleh ditanya.",
    range: "Al-Anbiya 21:1-112",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "al-hajj",
    number: "022",
    surahNumber: 22,
    title: "Al-Hajj",
    subtitle: "Ritual Tubuh, Kurban, Perang, dan Wahyu yang Diganggu",
    excerpt:
      "Al-Hajj memadukan kiamat, embriologi, Ka'bah, haji, kurban, izin perang, dan ayat tentang setan yang menyusupkan gangguan ke dalam wahyu. Surat ini menautkan ritual dengan kuasa.",
    range: "Al-Hajj 22:1-78",
    classification: "Madaniyah",
    readTime: "14 menit",
  },
  {
    slug: "al-muminun",
    number: "023",
    surahNumber: 23,
    title: "Al-Mu'minun",
    subtitle: "Tubuh, Seksualitas, Embriologi, dan Neraka yang Menutup Dialog",
    excerpt:
      "Al-Mu'minun membuka dengan ciri orang beriman, lalu masuk ke seksualitas, embriologi, tujuh langit, Nuh, Musa, Isa-Maryam, dan akhirat. Surat ini menjadikan tubuh sebagai medan iman.",
    range: "Al-Mu'minun 23:1-118",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "an-nur",
    number: "024",
    surahNumber: 24,
    title: "An-Nur",
    subtitle: "Tubuh, Fitnah, dan Politik Kepatuhan",
    excerpt:
      "An-Nur sering diingat lewat ayat cahaya. Tetapi surat ini juga memuat dera zina, empat saksi, li'an, kisah ifk, aturan pandangan, budak, aurat rumah tangga, dan ketaatan pada Rasul.",
    range: "An-Nur 24:1-64",
    classification: "Madaniyah",
    readTime: "13 menit",
  },
  {
    slug: "al-furqan",
    number: "025",
    surahNumber: 25,
    title: "Al-Furqan",
    subtitle: "Pembeda, Tuduhan Lama, dan Ancaman yang Berulang",
    excerpt:
      "Al-Furqan membela wahyu dengan menolak tuduhan dongeng lama, menekan skeptisisme lewat neraka, lalu memakai alam dan sifat hamba ideal sebagai pembeda komunitas.",
    range: "Al-Furqan 25:1-77",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "asy-syuara",
    number: "026",
    surahNumber: 26,
    title: "Asy-Syu'ara'",
    subtitle: "Kisah yang Diulang dan Penyair yang Dijinakkan",
    excerpt:
      "Asy-Syu'ara' membangun pola berulang: nabi datang, kaum menolak, hukuman turun, lalu peringatan diulang. Di akhir, penyair dikritik kecuali jika masuk pagar iman.",
    range: "Asy-Syu'ara 26:1-227",
    classification: "Makkiyah",
    readTime: "15 menit",
  },
  {
    slug: "an-naml",
    number: "027",
    surahNumber: 27,
    title: "An-Naml",
    subtitle: "Semut, Kerajaan, dan Bukti yang Berubah Jadi Kuasa",
    excerpt:
      "An-Naml memuat Musa, Sulaiman, semut, hudhud, Ratu Saba, dan rangkaian tanda alam. Surat ini memperlihatkan bagaimana mukjizat, pengetahuan gaib, dan politik kerajaan bercampur.",
    range: "An-Naml 27:1-93",
    classification: "Makkiyah",
    readTime: "14 menit",
  },
  {
    slug: "al-qasas",
    number: "028",
    surahNumber: 28,
    title: "Al-Qasas",
    subtitle: "Musa, Pelarian, dan Kebenaran yang Dipilihkan",
    excerpt:
      "Al-Qasas kembali ke kisah Musa: bayi di sungai, pembunuhan orang Mesir, pelarian ke Madyan, wahyu, Firaun-Haman, Qarun, dan penutup tentang pilihan Allah atas manusia.",
    range: "Al-Qasas 28:1-88",
    classification: "Makkiyah",
    readTime: "15 menit",
  },
  {
    slug: "al-ankabut",
    number: "029",
    surahNumber: 29,
    title: "Al-'Ankabut",
    subtitle: "Ujian Iman, Jaring Lemah, dan Sejarah Hukuman",
    excerpt:
      "Al-'Ankabut berbicara tentang ujian iman, konflik keluarga, rangkaian nabi, dan perumpamaan rumah laba-laba. Surat ini menjadikan keteguhan sebagai ukuran kebenaran, tetapi juga menutup banyak ruang ragu.",
    range: "Al-'Ankabut 29:1-69",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "ar-rum",
    number: "030",
    surahNumber: 30,
    title: "Ar-Rum",
    subtitle: "Kemenangan, Fitrah, dan Alam yang Dipaksa Jadi Bukti",
    excerpt:
      "Ar-Rum membuka dengan kekalahan dan kemenangan Romawi, lalu bergerak ke tanda-tanda alam, fitrah, rezeki, kerusakan bumi, dan hati yang dikunci. Surat ini memakai sejarah dan alam sebagai argumen iman.",
    range: "Ar-Rum 30:1-60",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "luqman",
    number: "031",
    surahNumber: 31,
    title: "Luqman",
    subtitle: "Nasihat Ayah, Hikmah, dan Batas Ketaatan",
    excerpt:
      "Luqman memadukan klaim kitab hikmah, kritik pada hiburan yang menyesatkan, nasihat ayah kepada anak, ketaatan kepada orang tua, dan argumen alam yang berulang.",
    range: "Luqman 31:1-34",
    classification: "Makkiyah",
    readTime: "11 menit",
  },
  {
    slug: "as-sajdah",
    number: "032",
    surahNumber: 32,
    title: "As-Sajdah",
    subtitle: "Penciptaan, Sujud, dan Tubuh yang Diadili",
    excerpt:
      "As-Sajdah berbicara tentang kitab yang tidak diragukan, penciptaan manusia dari tanah dan air hina, sujud, kebangkitan, dan neraka. Surat ini pendek, tetapi tegang dalam soal tubuh dan bukti.",
    range: "As-Sajdah 32:1-30",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
  {
    slug: "al-ahzab",
    number: "033",
    surahNumber: 33,
    title: "Al-Ahzab",
    subtitle: "Perang, Rumah Nabi, Hijab, dan Otoritas Personal",
    excerpt:
      "Al-Ahzab adalah surat yang sangat sosial-politik: perang parit, adopsi, Zainab, istri-istri Nabi, hijab, etika bertamu, dan kepatuhan kepada Rasul.",
    range: "Al-Ahzab 33:1-73",
    classification: "Madaniyah",
    readTime: "15 menit",
  },
  {
    slug: "saba",
    number: "034",
    surahNumber: 34,
    title: "Saba'",
    subtitle: "Kerajaan, Jin, Banjir, dan Dialog Akhirat",
    excerpt:
      "Saba' menggabungkan pengetahuan Allah, kisah Daud-Sulaiman, jin, kaum Saba, Iblis, rezeki, kelas sosial, dan dialog akhirat. Surat ini bergerak antara legenda kerajaan dan polarisasi iman.",
    range: "Saba 34:1-54",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "fatir",
    number: "035",
    surahNumber: 35,
    title: "Fatir",
    subtitle: "Penciptaan, Malaikat, dan Ancaman yang Ditunda",
    excerpt:
      "Fatir membuka dengan Allah sebagai pencipta langit-bumi dan malaikat bersayap, lalu membahas tipu daya dunia, tanda alam, pewaris kitab, dan ancaman yang ditangguhkan.",
    range: "Fatir 35:1-45",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "ya-sin",
    number: "036",
    surahNumber: 36,
    title: "Ya Sin",
    subtitle: "Peringatan, Predestinasi, dan Kosmologi Lama",
    excerpt:
      "Ya Sin bergerak dari pembelaan wahyu menuju gambaran orang kafir yang telah tertutup, kisah negeri anonim, tanda-tanda alam, kebangkitan, dan ancaman akhirat.",
    range: "Ya Sin 36:1-83",
    classification: "Makkiyah",
    readTime: "11 menit",
  },
  {
    slug: "as-saffat",
    number: "037",
    surahNumber: 37,
    title: "As-Saffat",
    subtitle: "Langit yang Dijaga, Neraka yang Dipertontonkan",
    excerpt:
      "As-Saffat memulai argumennya dari sumpah malaikat dan langit yang dijaga dari setan, lalu bergerak ke kebangkitan, surga-neraka, dan rangkaian kisah nabi.",
    range: "As-Saffat 37:1-182",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "sad",
    number: "038",
    surahNumber: 38,
    title: "Sad",
    subtitle: "Kuasa, Peringatan, dan Narasi yang Retak",
    excerpt:
      "Sad mempertemukan polemik Quraisy, kisah Daud, Sulaiman, Ayyub, neraka, dan dialog Iblis. Banyak bagiannya bertumpu pada peringatan, otoritas, dan hukuman.",
    range: "Sad 38:1-88",
    classification: "Makkiyah",
    readTime: "11 menit",
  },
  {
    slug: "az-zumar",
    number: "039",
    surahNumber: 39,
    title: "Az-Zumar",
    subtitle: "Agama Murni dan Manusia yang Digiring Berkelompok",
    excerpt:
      "Az-Zumar menekankan keikhlasan agama hanya untuk Allah, tetapi membangunnya lewat dikotomi tajam: petunjuk dan kesesatan, takut dan ampunan, neraka dan surga.",
    range: "Az-Zumar 39:1-75",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "gafir",
    number: "040",
    surahNumber: 40,
    title: "Gafir",
    subtitle: "Debat yang Dilarang dan Pengadilan yang Menutup Jalan Pulang",
    excerpt:
      "Gafir membuka dengan Tuhan yang mengampuni sekaligus keras menghukum, lalu menolak perdebatan atas ayat, menampilkan dialog neraka, Musa-Firaun, dan iman yang terlambat.",
    range: "Gafir 40:1-85",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "fussilat",
    number: "041",
    surahNumber: 41,
    title: "Fussilat",
    subtitle: "Kitab Terperinci, Kosmologi Lama, dan Tubuh yang Bersaksi",
    excerpt:
      "Fussilat membela Quran sebagai kitab Arab yang terperinci, tetapi memuat huruf misterius, kosmologi bumi-langit, hukuman kaum lama, dan tubuh yang menjadi saksi melawan dirinya sendiri.",
    range: "Fussilat 41:1-54",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "asy-syura",
    number: "042",
    surahNumber: 42,
    title: "Asy-Syura",
    subtitle: "Musyawarah, Wahyu, dan Kesesatan yang Dibiarkan",
    excerpt:
      "Asy-Syura memuat gagasan musyawarah dan pemaafan, tetapi juga menutup debat agama dengan ancaman, membahas rezeki sebagai kontrol ilahi, dan menyebut Allah membiarkan manusia sesat.",
    range: "Asy-Syura 42:1-53",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "az-zukhruf",
    number: "043",
    surahNumber: 43,
    title: "Az-Zukhruf",
    subtitle: "Kemewahan, Bahasa Arab, dan Polemik Anak Tuhan",
    excerpt:
      "Az-Zukhruf mengkritik kemewahan dan warisan nenek moyang, menegaskan Quran Arab, lalu bergerak ke kisah Musa-Firaun, Isa, dan polemik anak Tuhan.",
    range: "Az-Zukhruf 43:1-89",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "ad-dukhan",
    number: "044",
    surahNumber: 44,
    title: "Ad-Dukhan",
    subtitle: "Asap, Malam Berkah, dan Neraka yang Sadistik",
    excerpt:
      "Ad-Dukhan membangun klaim wahyu pada malam diberkahi, mengancam dengan asap dan hantaman besar, lalu menampilkan Musa-Firaun, skeptisisme kebangkitan, dan neraka zaqqum.",
    range: "Ad-Dukhan 44:1-59",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "al-jasiyah",
    number: "045",
    surahNumber: 45,
    title: "Al-Jasiyah",
    subtitle: "Tanda Alam, Syariat, dan Manusia yang Berlutut",
    excerpt:
      "Al-Jasiyah memakai tanda alam, sejarah Bani Israel, syariat, dan kritik pada orang yang menjadikan hawa nafsu sebagai tuhan, lalu menutup dengan umat-umat yang berlutut menunggu catatan amal.",
    range: "Al-Jasiyah 45:1-37",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "al-ahqaf",
    number: "046",
    surahNumber: 46,
    title: "Al-Ahqaf",
    subtitle: "Bukit Pasir, Jin, dan Ancaman yang Mengganti Bukti",
    excerpt:
      "Al-Ahqaf membela wahyu lewat kitab Musa, kisah Ad, kesaksian jin, dan ancaman akhirat, sambil memperlakukan skeptisisme sebagai pembangkangan yang pantas dihukum.",
    range: "Al-Ahqaf 46:1-35",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "muhammad",
    number: "047",
    surahNumber: 47,
    title: "Muhammad",
    subtitle: "Perang, Leher, dan Surga sebagai Kontrak",
    excerpt:
      "Muhammad bergerak dari pembatalan amal orang kafir ke perintah perang, tawanan, surga sungai-sungai, stigma munafik, dan larangan meminta damai saat posisi unggul.",
    range: "Muhammad 47:1-38",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "al-fath",
    number: "048",
    surahNumber: 48,
    title: "Al-Fath",
    subtitle: "Kemenangan Politik, Baiat, dan Rampasan",
    excerpt:
      "Al-Fath membaca Hudaibiyah sebagai kemenangan, menata loyalitas politik, menghakimi Badui yang tertinggal, menjanjikan rampasan, dan memuji ketegasan terhadap orang kafir.",
    range: "Al-Fath 48:1-29",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "al-hujurat",
    number: "049",
    surahNumber: 49,
    title: "Al-Hujurat",
    subtitle: "Adab Komunitas dan Batas Kritik",
    excerpt:
      "Al-Hujurat memuat etika sosial yang sering terdengar indah, tetapi juga menempatkan Nabi di atas percakapan biasa, mengatur konflik, dan mengawasi iman komunitas.",
    range: "Al-Hujurat 49:1-18",
    classification: "Madaniyah",
    readTime: "11 menit",
  },
  {
    slug: "qaf",
    number: "050",
    surahNumber: 50,
    title: "Qaf",
    subtitle: "Kebangkitan, Pengawasan, dan Neraka yang Minta Tambahan",
    excerpt:
      "Qaf menjawab skeptisisme kebangkitan dengan tanda alam, catatan malaikat, pengadilan tanpa banding, dan neraka yang digambarkan masih meminta tambahan.",
    range: "Qaf 50:1-45",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "az-zariyat",
    number: "051",
    surahNumber: 51,
    title: "Az-Zariyat",
    subtitle: "Sumpah Alam, Bencana Lama, dan Manusia sebagai Hamba",
    excerpt:
      "Az-Zariyat memakai sumpah angin, langit, rezeki, kisah Ibrahim-Lut, kehancuran kaum lama, dan tujuan penciptaan manusia-jin sebagai ibadah.",
    range: "Az-Zariyat 51:1-60",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "at-tur",
    number: "052",
    surahNumber: 52,
    title: "At-Tur",
    subtitle: "Gunung, Azab Pasti, dan Tantangan yang Tidak Netral",
    excerpt:
      "At-Tur membuka dengan sumpah beruntun, menegaskan azab yang tidak bisa ditolak, lalu membangun kontras surga-neraka dan rentetan pertanyaan retoris kepada penolak wahyu.",
    range: "At-Tur 52:1-49",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "an-najm",
    number: "053",
    surahNumber: 53,
    title: "An-Najm",
    subtitle: "Wahyu Personal, Dewi Arab, dan Otoritas yang Menutup Kritik",
    excerpt:
      "An-Najm membela pengalaman wahyu Muhammad, menolak Latta-Uzza-Manat, memakai kritik berbasis gender, lalu menutup dengan kuasa Tuhan atas hidup, mati, dan kehancuran kaum lama.",
    range: "An-Najm 53:1-62",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "al-qamar",
    number: "054",
    surahNumber: 54,
    title: "Al-Qamar",
    subtitle: "Bulan Terbelah dan Repetisi Azab",
    excerpt:
      "Al-Qamar memakai tanda bulan terbelah, kisah Nuh, Ad, Samud, Lut, dan Firaun, dengan repetisi peringatan yang menjadikan kehancuran massal sebagai pelajaran.",
    range: "Al-Qamar 54:1-55",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "ar-rahman",
    number: "055",
    surahNumber: 55,
    title: "Ar-Rahman",
    subtitle: "Nikmat yang Diulang dan Kekerasan yang Ikut Disebut Nikmat",
    excerpt:
      "Ar-Rahman terkenal dengan repetisi nikmat Tuhan, tetapi di dalamnya juga ada kosmologi lama, ancaman api dan tembaga panas, neraka, serta surga yang sangat material dan patriarkal.",
    range: "Ar-Rahman 55:1-78",
    classification: "Madaniyah",
    readTime: "13 menit",
  },
  {
    slug: "al-waqiah",
    number: "056",
    surahNumber: 56,
    title: "Al-Waqi'ah",
    subtitle: "Tiga Kelas Manusia dan Surga yang Sangat Material",
    excerpt:
      "Al-Waqi'ah membagi manusia menjadi tiga golongan, menggambarkan surga dengan kemewahan dan bidadari, lalu menekan skeptisisme kebangkitan lewat neraka dan kematian.",
    range: "Al-Waqi'ah 56:1-96",
    classification: "Makkiyah",
    readTime: "13 menit",
  },
  {
    slug: "al-hadid",
    number: "057",
    surahNumber: 57,
    title: "Al-Hadid",
    subtitle: "Besi, Infak, Cahaya, dan Dunia yang Direndahkan",
    excerpt:
      "Al-Hadid menyatukan kuasa kosmik Allah, seruan infak, hierarki perang, cahaya mukmin, dinding munafik, takdir bencana, besi, dan kritik terhadap Ahli Kitab.",
    range: "Al-Hadid 57:1-29",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "al-mujadilah",
    number: "058",
    surahNumber: 58,
    title: "Al-Mujadilah",
    subtitle: "Zihar, Bisik-Bisik, dan Loyalitas yang Memutus Keluarga",
    excerpt:
      "Al-Mujadilah membuka dengan kasus zihar, lalu bergerak ke hukum kafarat, pengawasan percakapan rahasia, akses kepada Rasul, label munafik, dan loyalitas ideologis.",
    range: "Al-Mujadilah 58:1-22",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "al-hasyr",
    number: "059",
    surahNumber: 59,
    title: "Al-Hasyr",
    subtitle: "Pengusiran, Fai, dan Teologi Penaklukan",
    excerpt:
      "Al-Hasyr membaca pengusiran Bani Nadir sebagai tindakan ilahi, membahas penebangan kurma, rampasan fai, solidaritas internal, munafik, dan nama-nama Allah.",
    range: "Al-Hasyr 59:1-24",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "al-mumtahanah",
    number: "060",
    surahNumber: 60,
    title: "Al-Mumtahanah",
    subtitle: "Loyalitas, Permusuhan, dan Perempuan di Batas Politik",
    excerpt:
      "Al-Mumtahanah mengatur relasi dengan musuh, menjadikan Ibrahim contoh pemisahan, memberi celah berbuat adil, lalu menguji perempuan hijrah dan memutus nikah lintas iman.",
    range: "Al-Mumtahanah 60:1-13",
    classification: "Madaniyah",
    readTime: "12 menit",
  },
  {
    slug: "as-saff",
    number: "061",
    surahNumber: 61,
    title: "As-Saff",
    subtitle: "Barisan Perang, Perdagangan Surga, dan Nama yang Dimasukkan ke Mulut Isa",
    excerpt:
      "As-Saff menegur inkonsistensi antara ucapan dan perbuatan, lalu memuji formasi perang, menawarkan iman sebagai perdagangan, dan mengklaim bahwa Isa pernah meramalkan kedatangan Ahmad.",
    range: "As-Saff 61:1-14",
    classification: "Madaniyah",
    readTime: "10 menit",
  },
  {
    slug: "al-jumuah",
    number: "062",
    surahNumber: 62,
    title: "Al-Jumu'ah",
    subtitle: "Keledai, Kematian, dan Panggilan Jumat",
    excerpt:
      "Al-Jumu'ah bergerak dari misi kepada kaum buta huruf, perumpamaan keledai untuk yang tidak mengamalkan Taurat, tantangan kematian, hingga perintah meninggalkan perdagangan saat azan Jumat.",
    range: "Al-Jumu'ah 62:1-11",
    classification: "Madaniyah",
    readTime: "10 menit",
  },
  {
    slug: "al-munafiqun",
    number: "063",
    surahNumber: 63,
    title: "Al-Munafiqun",
    subtitle: "Hati yang Dikunci dan Kategori yang Tidak Bisa Berubah",
    excerpt:
      "Al-Munafiqun merespons krisis kepercayaan internal di Madinah dengan bahasa yang keras: hati dikunci, vonis tidak terampuni, dan perumpamaan yang menurunkan martabat target kritiknya.",
    range: "Al-Munafiqun 63:1-11",
    classification: "Madaniyah",
    readTime: "10 menit",
  },
  {
    slug: "at-taghabun",
    number: "064",
    surahNumber: 64,
    title: "At-Taghabun",
    subtitle: "Hari Kerugian, Ciptaan yang Dihukum, dan Keluarga sebagai Ujian",
    excerpt:
      "At-Taghabun memuat pernyataan berat bahwa Allah menciptakan mukmin dan kafir, lalu menetapkan hukuman kekal bagi kafir. Di tengahnya ada nasihat tentang musibah, keluarga, dan pinjaman kepada Tuhan.",
    range: "At-Taghabun 64:1-18",
    classification: "Madaniyah",
    readTime: "11 menit",
  },
  {
    slug: "at-talaq",
    number: "065",
    surahNumber: 65,
    title: "At-Talaq",
    subtitle: "Hukum Cerai, Iddah, dan Sistem yang Menempatkan Perempuan",
    excerpt:
      "At-Talaq mengatur perceraian, iddah, tempat tinggal, dan nafkah dengan rinci. Di dalamnya ada ketentuan iddah bagi perempuan yang belum haid dan kosmologi tujuh langit-bumi.",
    range: "At-Talaq 65:1-12",
    classification: "Madaniyah",
    readTime: "11 menit",
  },
  {
    slug: "at-tahrim",
    number: "066",
    surahNumber: 66,
    title: "At-Tahrim",
    subtitle: "Rumah Tangga Nabi, Bocoran Rahasia, dan Kekuatan Kosmik di Sisi Suami",
    excerpt:
      "At-Tahrim dimulai dengan Allah menegur Nabi yang melarang dirinya dari yang halal demi menyenangkan istri. Dari sana surat bergerak ke rahasia yang dibocorkan, ancaman mengganti istri, dan perumpamaan tentang perempuan yang layak dan tidak.",
    range: "At-Tahrim 66:1-12",
    classification: "Madaniyah",
    readTime: "11 menit",
  },
  {
    slug: "al-mulk",
    number: "067",
    surahNumber: 67,
    title: "Al-Mulk",
    subtitle: "Kepemilikan, Pengawasan, dan Ketakutan sebagai Fondasi Kepatuhan",
    excerpt:
      "Al-Mulk membangun gambaran Allah yang menguasai kerajaan, menguji manusia melalui kematian dan kehidupan, mengawasi setiap pikiran, dan memotivasi kepatuhan melalui ancaman neraka, bumi yang menelan, dan air yang bisa ditahan.",
    range: "Al-Mulk 67:1-30",
    classification: "Makkiyah",
    readTime: "11 menit",
  },
  {
    slug: "al-qalam",
    number: "068",
    surahNumber: 68,
    title: "Al-Qalam",
    subtitle: "Pena, Tuduhan Gila, dan Kisah Kebun yang Hangus",
    excerpt:
      "Al-Qalam dimulai dengan membela Muhammad dari tuduhan gila lalu membalikkan tuduhan itu kepada penentang. Surat ini juga membangun profil negatif para penolak dan menceritakan kisah kebun yang hancur karena pemiliknya menghalangi orang miskin.",
    range: "Al-Qalam 68:1-52",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "al-haqqah",
    number: "069",
    surahNumber: 69,
    title: "Al-Haqqah",
    subtitle: "Kepastian Kiamat, Pemusnahan Massal, dan Argumen yang Berputar",
    excerpt:
      "Al-Haqqah membuka dengan hari yang pasti terjadi, lalu mendukungnya dengan cerita kehancuran kolektif kaum Samud, Ad, dan Firaun. Di ujungnya Al-Quran membela dirinya sendiri sebagai wahyu melalui argumen yang bersandar pada otoritas yang sedang diklaim.",
    range: "Al-Haqqah 69:1-52",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "al-maarij",
    number: "070",
    surahNumber: 70,
    title: "Al-Ma'arij",
    subtitle: "Skala Kosmik, Manusia yang Kikir, dan Hamba Sahaya yang Dilegalkan",
    excerpt:
      "Al-Ma'arij bermain dengan skala: satu hari setara lima puluh ribu tahun, langit mencair, gunung beterbangan. Di tengahnya ada gambaran manusia yang bersedia mengorbankan keluarganya sendiri untuk selamat, dan daftar kriteria keselamatan yang mencakup legitimasi atas hamba sahaya.",
    range: "Al-Ma'arij 70:1-44",
    classification: "Makkiyah",
    readTime: "12 menit",
  },
  {
    slug: "nuh",
    number: "071",
    surahNumber: 71,
    title: "Nuh",
    subtitle: "Doa Genosida, Bumi Datar, dan Determinisme Genetik Kafir",
    excerpt:
      "Nuh berdakwah berabad-abad, lalu mengakhiri kesabarannya dengan doa agar tidak ada satu pun orang kafir yang tersisa di bumi — karena mereka hanya akan melahirkan anak yang jahat. Surat ini adalah legitimasi pemusnahan massal sebagai respons logis terhadap penolakan dakwah.",
    range: "Nuh 71:1-28",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
  {
    slug: "al-jinn",
    number: "072",
    surahNumber: 72,
    title: "Al-Jinn",
    subtitle: "Saksi yang Tak Bisa Dihadirkan dan Epistemologi Tertutup",
    excerpt:
      "Al-Jinn menggunakan kesaksian makhluk yang tidak bisa dilihat, diinterogasi, atau dibantah sebagai bukti kebenaran Al-Qur'an. Sistem epistemologis yang dibangunnya tidak memiliki titik masuk dari luar — kebenaran hanya bisa dikonfirmasi melalui klaim yang ingin dibuktikannya sendiri.",
    range: "Al-Jinn 72:1-28",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
  {
    slug: "al-muzzammil",
    number: "073",
    surahNumber: 73,
    title: "Al-Muzzammil",
    subtitle: "Perintah yang Direvisi, Pinjaman kepada Allah, dan Azab sebagai Persuasi",
    excerpt:
      "Al-Muzzammil memerintahkan shalat malam dengan durasi yang sangat spesifik, lalu mencabut hampir seluruh perintah itu di ayat terakhir. Surat ini juga meminta manusia memberikan pinjaman kepada entitas yang diklaim pemilik segala sesuatu.",
    range: "Al-Muzzammil 73:1-20",
    classification: "Makkiyah",
    readTime: "9 menit",
  },
  {
    slug: "al-muddassir",
    number: "074",
    surahNumber: 74,
    title: "Al-Muddassir",
    subtitle: "Penyelesaian Skor Personal, 19 Penjaga, dan Kafir sebagai Keledai",
    excerpt:
      "Al-Muddassir adalah surat tentang amarah yang sangat personal terhadap al-Walid bin Mughirah yang menyebut Al-Qur'an sihir. Allah menciptakannya, memberinya segalanya, lalu mengancam neraka Saqar karena ia berpikir kritis. Surat ini juga secara eksplisit menyatakan Allah menyesatkan orang-orang yang dikehendaki-Nya.",
    range: "Al-Muddassir 74:1-56",
    classification: "Makkiyah",
    readTime: "11 menit",
  },
  {
    slug: "al-qiyamah",
    number: "075",
    surahNumber: 75,
    title: "Al-Qiyamah",
    subtitle: "Astronomi yang Salah, Embriologi Parsial, dan Kutukan sebagai Argumen",
    excerpt:
      "Al-Qiyamah menggambarkan matahari dan bulan yang dikumpulkan, bulan kehilangan cahayanya, manusia yang dihalau seperti ternak menghadap Allah. Argumen utamanya bukan penalaran melainkan kutukan berulang: celakalah kamu, maka celakalah.",
    range: "Al-Qiyamah 75:1-40",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
  {
    slug: "al-insan",
    number: "076",
    surahNumber: 76,
    title: "Al-Insan",
    subtitle: "Eksperimen Moral Bermasalah, Surga Arab, dan Kehendak yang Dicabut",
    excerpt:
      "Al-Insan menciptakan manusia untuk diuji dengan konsekuensi kekal, menawarkan surga berisi kafur, jahe, sutra, dan pemuda-pemuda abadi, lalu mencabut kehendak bebas dalam satu ayat: kamu tidak mampu menghendaki kecuali apabila dikehendaki Allah.",
    range: "Al-Insan 76:1-31",
    classification: "Madaniyah",
    readTime: "10 menit",
  },
  {
    slug: "al-mursalat",
    number: "077",
    surahNumber: 77,
    title: "Al-Mursalat",
    subtitle: "Sebelas Kali Celaka, Air yang Hina, dan Peradilan Tanpa Pembelaan",
    excerpt:
      "Al-Mursalat mengulang ancaman celakalah sebelas kali dalam satu surat — repetisi sebagai pengganti argumen. Di antaranya: manusia dari air yang hina, terdakwa tidak diizinkan membela diri, dan kafir diajak sarkastis makan dan bersenang-senang sebentar.",
    range: "Al-Mursalat 77:1-50",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
  {
    slug: "an-naba",
    number: "078",
    surahNumber: 78,
    title: "An-Naba",
    subtitle: "Gunung sebagai Pasak, Gadis Belia sebagai Hadiah, dan Bahasa Sadistik",
    excerpt:
      "An-Naba membuat klaim geologi dan astronomi yang salah, menawarkan gadis-gadis belia sebaya sebagai komponen hadiah surga bagi laki-laki beriman, dan menutup neraka dengan perintah: rasakanlah, tidak ada yang akan Kami tambahkan selain azab.",
    range: "An-Naba 78:1-40",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
  {
    slug: "an-naziat",
    number: "079",
    surahNumber: 79,
    title: "An-Nazi'at",
    subtitle: "Sumpah Ambigu, Firaun yang Dikarturisasi, dan Kiamat yang Tidak Bisa Ditanya",
    excerpt:
      "An-Nazi'at bersumpah dengan objek yang tidak jelas, menempatkan penciptaan langit sebelum bumi yang bertentangan dengan kosmologi modern, dan menjawab pertanyaan kapan kiamat dengan: untuk apa engkau menyebutkannya? Penghindaran adalah cara mempertahankan klaim yang tidak bisa diuji.",
    range: "An-Nazi'at 79:1-46",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
  {
    slug: "abasa",
    number: "080",
    surahNumber: 80,
    title: "Abasa",
    subtitle: "Nabi yang Mengutamakan Pembesar, Embriologi Parsial, dan Keluarga yang Lari",
    excerpt:
      "Abasa mendokumentasikan Muhammad yang berpaling dari orang buta demi menjamu pembesar Quraisy — bias status sosial yang perlu dikoreksi wahyu. Surat ini juga menggambarkan kiamat di mana manusia lari dari ibu, bapak, istri, dan anak-anaknya sendiri.",
    range: "Abasa 80:1-42",
    classification: "Makkiyah",
    readTime: "10 menit",
  },
];

export function getBedahSuratItem(slug: string) {
  return bedahSuratItems.find((item) => item.slug === slug);
}
